[package]
name = "fake_proxy_service"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
